### ISSUE TITLE
Unknown CMake command "pybind11_add_module"

### ISSUE THREAD

**Issue by wyang20170113** [tdegeus/pybind11_examples#1]
when i run 'cmake .', i get this error: Unknown CMake command "pybind11_add_module"

**Comment by tdegeus** [comment]
I see that you have managed!?! You could summarize the problem and the solution here for future reference?

**Comment by wyang20170113** [comment]
Yes, I just copy pybind11 to each example, then run cmake and all the examples can be successfully complied.
