### ISSUE TITLE
pyBind11 performance issue's [solved]

### ISSUE THREAD

**Issue by grotius-cnc** [tdegeus/pybind11_examples#11]
Hi,

I used pyBind11 example to create a binding to transferr openGl image data.
Everything went well. The examples provided here where usefull, thanks for that !

The runtime performance of the pyBind11 library was bad, very bad, maybe it's a good idea to
mention that in this repository so users can make a choice.

I duckducked for "pyBind11 slow"  and indeed more people
where complaining. One reply on stackoverflow hinted that it had nothing to do with pyBind11. 

My solution was to write my own python - c++ binding. The performance is outstanding.

My code below is derived from this example : https://www.geeksforgeeks.org/how-to-call-c-c-from-python/

My python c++ binding with perfect performance :
The c++ binding : https://github.com/grotius-cnc/XCreator/blob/main/XLcncClientServer/XClient/XBind.cpp
The python binding : https://github.com/grotius-cnc/XCreator/blob/main/XLcncClientServer/XClient/patch/skynet.py

**Comment by tdegeus** [comment]
Thanks for documentation
